apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-root-username: dXNlcm5hbWU= 
  mongodb-root-password: cGFzc3dvcmQ=
  # password: {{ .Values.password | b64enc }}